### ISSUE TITLE
ukol 2

### ISSUE THREAD

**Issue by KarolinaNeumann** [KarolinaNeumann/Python_2024#2]
Ahoj Evgeniye, 
potřebovala bych prosím pomoct s úkolem 2 - zadání část 2.
Dostala jsem se k tomu, že jsem sepsala skript:
- který funguje, při zavolání na příklad "Moneta" (ukol2_cast2_moneta.py)
- který má vstup - input a umí vyhledávat subjekty a vypsat o nich informace (ukol2_cast2_vyhledavani.py) 
zkoušela jsem zadat do inputu "jakub neumann" a našlo mi to celkem 15 subjektů, výpis má (na mě moc) složitou strukturu slovník se vnořenými seznamy i slovníky- 1. nalezený subjekt jsem si pokusila upravit do přehlednější verze (ukol2_cast2_vyhledavani-seznam.py).
Nevím, jak dál pokračovat, měla jsem v úmyslu procházet data for cyklem, ale nevím, jak takhle nastavenou strukturu procházet. Mohla bych tě poprosit o nasměrování? 
díky Kája
https://github.com/KarolinaNeumann/Python_2024/tree/main/PY2024_ukol2

**Comment by evgeniyako-edu** [comment]
Ahoj,

super, tady je pár poznámek.

**část 1**

```
# prevod slovniku (s nazvem data) na .json - obsahuje jiz konkretni data o subjektu
with open ("subjekt.json", mode = "w", encoding = "utf-8") as file: 
    json.dump(data, file, ensure_ascii = False)
```
Myslím si, že ten převod už jsi udělala předtím, když jsi napsala `data = response.json()`. Takže mohla jsi hned vypsat `print(data["obchodniJmeno"] + ", " + data["sidlo"]["textovaAdresa"])`.

Ale samozřejmě je v pořádku, když tento výstup napřed uložíš, může se to hodit.

**PY2024_ukol2/ukol2_cast2-vyhledavani.py**

```
for subjekt in data["ekonomickeSubjekty"]:
   print()
```
Ten `print()` je prázdný, takže zatím nic nevypisuje. Chtěli bychom tam vypsat názvy těch firem.  

`data["ekonomickeSubjekty"]` je seznam slovniků. Každý ten slovník (máš ho na každé iteraci uložený do proměnné `subjekt`) odpovídá jednomu subjektu. Název tohoto subjektu najdeme podle klíče `"obchodniJmeno"`, takže asi tam potřebuješ vypsat `subjekt["obchodniJmeno"]`. 

Zkusíš to? Můžeš k tomu názvu vypsat ještě ičo (klíč "ico").

**Comment by KarolinaNeumann** [comment]
Díky moc za popis, zamotala jsem se v tom for cyklu. už to klape <3 
za mě tedy asi hotovo :)
https://github.com/KarolinaNeumann/Python_2024/tree/main/PY2024_ukol2

**Comment by KarolinaNeumann** [comment]
zkusím ještě udělat bonus, ale nejsem si jistá že na to bude prostor,  Když se mi ho podaří dotáhnout, dám vědět :)

**Comment by evgeniyako-edu** [comment]
Je to dobrý, všechno v pořádku!
